version: '3'
services:
 mongo:
    image: mongo:4.4.6
    container_name: donation_db
    environment:
      - MONGO_INITDB_DATABASE=donations
    volumes:
      - ./container-volumes/mongo:/data/db
    ports:
      - '27017:27017'